### ISSUE TITLE
Customer Registration Step-2 , Getting 400 error code

### ISSUE THREAD

**Issue by Shahiddbbl** [tanvirshuvo/gigatech-ekyc-docs-and-resources#1]
Now we are getting 400 error code during Customer registration step 2 instead of 200. As discussed previously we got 500 which is resolved by you. Please look after the issue.

**Comment by tanvirshuvo** [comment]
Is there any message for the error?
I just checked and there is a error message stating the detail.

**Comment by tanvirshuvo** [comment]
The 400 (Bad Request) status code indicates that the server cannot or will not process the request due to something that is perceived to be a client error. Please check your request again to see if there is any field key or value related error. @Shahiddbbl 
Also we can not put this in 200. Since it is a bad request. Like when you get 403 unauthorized , that also means server is processing authentication and deciding that you are not authorized.

**Comment by Shahiddbbl** [comment]
We don't get any error message for this response code 400. For that reason we are not understanding what was the reason behind it. It would be better if you change the api response with handling the case with 200 and give status and message field. Also let me know if any kind of modification is done in api response in your side.

**Comment by tanvirshuvo** [comment]
Problem was the client side's challenge to grab the error message coming from 400 series. The reason of error are already in the message. Closing the issue.
